In [1]:
import numpy as np
#einsum 是numpy的一个函数，实现了爱因斯坦求和约定，可以实现多维数组的许多基本运算

# 向量

In [2]:
#向量内积(又叫数量积, 点乘)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.einsum("i,i->",a,b)
c

32

In [3]:
#向量矢积(又叫向量积, 叉乘)

e = np.zeros((3, 3, 3))
e[0, 1, 2] = e[1, 2, 0] = e[2, 0, 1] = 1
e[0, 2, 1] = e[2, 1, 0] = e[1, 0, 2] = -1


a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.einsum("i,j,ijk->k",a,b,e)
c

array([-3.,  6., -3.])

In [4]:
#向量外积(又叫张量积, 并失)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.einsum("i,j->ij",a,b)
c

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

# 矩阵

In [5]:
#矩阵求迹
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.einsum("ii->",a)
c

15

In [6]:
#矩阵求所有元素和
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.einsum("ij->",a)
c

45

In [7]:
#矩阵沿i方向(第0轴)求和
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.einsum("ij->j",a)
c

array([12, 15, 18])

In [8]:
#矩阵沿j方向(第1轴)求和
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.einsum("ij->i",a)
c

array([ 6, 15, 24])

In [9]:
#矩阵转置
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.einsum("ij->ji",a)
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
#矩阵相乘
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
c = np.einsum("ik,kj->ij",a,b)
c

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [11]:
#用矩阵表示的(二阶张量)张量积
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
c = np.einsum("ij,kl->ijkl",a,b)
c

array([[[[ 9,  8,  7],
         [ 6,  5,  4],
         [ 3,  2,  1]],

        [[18, 16, 14],
         [12, 10,  8],
         [ 6,  4,  2]],

        [[27, 24, 21],
         [18, 15, 12],
         [ 9,  6,  3]]],


       [[[36, 32, 28],
         [24, 20, 16],
         [12,  8,  4]],

        [[45, 40, 35],
         [30, 25, 20],
         [15, 10,  5]],

        [[54, 48, 42],
         [36, 30, 24],
         [18, 12,  6]]],


       [[[63, 56, 49],
         [42, 35, 28],
         [21, 14,  7]],

        [[72, 64, 56],
         [48, 40, 32],
         [24, 16,  8]],

        [[81, 72, 63],
         [54, 45, 36],
         [27, 18,  9]]]])

# 多维数组

In [12]:
#用三维数组表示的(三阶张量)缩并 后两个指标
a = np.array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14,  15],
         [ 16,  17,  18]],

        [[19, 20, 21],
         [22, 23, 24],
         [ 25,  26,  27]]])

c = np.einsum("ijk->i",a)
c

array([ 45, 126, 207])

# 函数文档

In [13]:
help(np.einsum)

Help on function einsum in module numpy:

einsum(*operands, **kwargs)
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
           casting='safe', optimize=False)
    
    Evaluates the Einstein summation convention on the operands.
    
    Using the Einstein summation convention, many common multi-dimensional,
    linear algebraic array operations can be represented in a simple fashion.
    In *implicit* mode `einsum` computes these values.
    
    In *explicit* mode, `einsum` provides further flexibility to compute
    other array operations that might not be considered classical Einstein
    summation operations, by disabling, or forcing summation over specified
    subscript labels.
    
    See the notes and examples for clarification.
    
    Parameters
    ----------
    subscripts : str
        Specifies the subscripts for summation as comma separated list of
        subscript labels. An implicit (classical Einstein summation)
        calculation is performe